site_name: yaml-lex Docs
site_description: Formats yml files formatted under corpus
site_author: Marcelino Veloso III
repo_url: https://github.com/justmars/yaml-lex
dev_addr: '127.0.0.1:8002'
theme:
  name: "material"
  features:
    - content.tabs.link
    - content.code.annotate
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: pink
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
nav:
  - Overview: index.md
extra:
  homepage: https://mv3.dev
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/justmars
      name: justmars on Github
    - icon: fontawesome/brands/mastodon
      link: https://esq.social/@mv
      name: mv on Mastodon
copyright: Copyright &copy; Marcelino Veloso III
plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_toc_entry: false
            show_category_heading: true
            show_source: true
            heading_level: 3
            inherited_members: true # added
            extra:
              crossref: true   # <-- move crossref here
  - search:
      lang: en
markdown_extensions:
  - footnotes
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      auto_title: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: pymdownx.superfences.fence_code_format
